# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: gkresic's pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

lang: en
timezone: Europe/Zagreb

markdown: kramdown
theme: jekyll-text-theme  # https://github.com/kitian616/jekyll-TeXt-theme

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      show_title: true
      show_date: false
      show_tags: false
      full_width: false
      excerpt_separator: <!--more-->

text_skin: default
highlight_theme: tomorrow

author:
  type      : person
  name      : Gordan Krešić
  bio       : Engineer by nurture, hacker by nature, übergeek by choice.
  email     : gordan.kresic@steatoda.com
  linkedin  : gkresic
  github    : gkresic
